# Generated by Django 5.2.6 on 2025-09-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_details', models.TextField()),
                ('task_date', models.DateTimeField()),
                ('task_is_complete', models.BooleanField(default=False)),
                ('task_priority', models.IntegerField(default=0)),
                ('task_location', models.CharField(max_length=100)),
                ('task_set_reminder', models.BooleanField(default=False)),
            ],
        ),
    ]
